services:
  # 构建基础镜像
  lx-music-api-server-base:
    build:
      context: .
      dockerfile: Dockerfile.base
      # 指定 build 阶段的网络
      network: host
    image: lx-music-api-server-base:latest
    profiles: ["build-base"]

  # 主服务
  lx-music-api-server:
    image: lx-music-api-server-base:latest
    container_name: lx-music-api-server
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "9763:9763"
    command: ["python", "main.py"]
    environment:
      - TZ=Asia/Shanghai
    networks:
      - lx-music-network



networks:
  lx-music-network:
    driver: bridge